// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo9BMVyOFBKtHgIJimSjuRCoLy7_BIz-c',
    appId: '1:917925633182:web:7e4a84ca6480815f21ef8f',
    messagingSenderId: '917925633182',
    projectId: 'travling-app-28d94',
    authDomain: 'travling-app-28d94.firebaseapp.com',
    databaseURL: 'https://travling-app-28d94-default-rtdb.firebaseio.com',
    storageBucket: 'travling-app-28d94.appspot.com',
    measurementId: 'G-PQYZEGD26H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD83Yv00TQU1kA3ZHGCGJFn9zMN_aYQnCs',
    appId: '1:917925633182:android:fe4659a2ddcbe85121ef8f',
    messagingSenderId: '917925633182',
    projectId: 'travling-app-28d94',
    databaseURL: 'https://travling-app-28d94-default-rtdb.firebaseio.com',
    storageBucket: 'travling-app-28d94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIYAg2BOS0YhVPZzbJMZFzLBUiB5arXX4',
    appId: '1:917925633182:ios:009aaa900abbde7721ef8f',
    messagingSenderId: '917925633182',
    projectId: 'travling-app-28d94',
    databaseURL: 'https://travling-app-28d94-default-rtdb.firebaseio.com',
    storageBucket: 'travling-app-28d94.appspot.com',
    androidClientId:
        '917925633182-71tfeps964ki9eiasf9v3fbb1u00rv46.apps.googleusercontent.com',
    iosClientId:
        '917925633182-ilm7dp48b0omb4kh52utcn4kjaa35658.apps.googleusercontent.com',
    iosBundleId: 'com.example.traellingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIYAg2BOS0YhVPZzbJMZFzLBUiB5arXX4',
    appId: '1:917925633182:ios:06fd8adb4901a87c21ef8f',
    messagingSenderId: '917925633182',
    projectId: 'travling-app-28d94',
    databaseURL: 'https://travling-app-28d94-default-rtdb.firebaseio.com',
    storageBucket: 'travling-app-28d94.appspot.com',
    androidClientId:
        '917925633182-71tfeps964ki9eiasf9v3fbb1u00rv46.apps.googleusercontent.com',
    iosClientId:
        '917925633182-0mmqepb4kebkogbrv57rq1imo05apjcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.traellingApp.RunnerTests',
  );
}
